spring:
  application:
    name: parking-control-db

  datasource:
    url: jdbc:postgresql://localhost:5432/parking-control-db
    username: postgres
    password: banco123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
